version: "3.7"

services:
  django-docker:
    container_name: django
    image: django-docker
    volumes:
      - ${HOME}/django-docker/myproject/:/app/myproject/
    ports:
      - "8090:8000"
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    networks:
      - net_django

  db:
    image: juliano777/postgres
    container_name: mydb
    volumes:
      - ./db/sql:/var/local/pgsql/scripts
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    networks:
      - net_django

networks:
  net_django:
    name: net_django
