version: "3.7"

services:

  db:
    image: juliano777/postgres
    container_name: mydb
    volumes:
    - ./sql:/var/local/pgsql/scripts
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    #command: 'pg_ctl start && runscripts.sh'
    networks:
      - mydjango

networks:
  mydjango:
